### ISSUE TITLE
15.0.3 crashing

### ISSUE THREAD

**Issue by TacoSundae84** [ValhelsiaTeam/Valhelsia-Structures#10]
After upgrading to the new version and exploring a bit, the game crashed. This happened consistently when trying to go into the same area, so I downgraded to the previous version, and it is no longer crashing. The crash logs were all the same, so just attaching one.

[crash-2020-06-02_10.27.39-server.txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/4718071/crash-2020-06-02_10.27.39-server.txt)

**Comment by Vaelzan** [comment]
Thanks for the report. This is a tough one, because that crash report indicates a vanilla bug that happens to be triggered by the mod being updated. I believe it's because we removed one structure that used to exist in the previous version, although I'm not absolutely certain. I might be able to work around it somehow though for the next update.

**Comment by Vaelzan** [comment]
Fixed in 14.0.4a and 15.0.3a, just released.
