### ISSUE TITLE
[1.15.2] Incompatible with Terraforged (VS 15.0.3)

### ISSUE THREAD

**Issue by sirgfsa** [ValhelsiaTeam/Valhelsia-Structures#11]
Minecraft: 1.15.2
Forge Version: 31.2.0
Mods Used:
TerraForged-1.15.2-0.0.14.jar
valhelsia_structures-15.0.3.jar

The 15.0.3 version seems to be incompatible with Terraforged. Structures do not seem to be spawning. The /locate command to locate the mod's structures results in gradually worse TPS lag until server/client times out. 15.0.2a seems to work fine though.

**Comment by Vaelzan** [comment]
Thanks for the report. I think this may be caused by some code that I added to whitelist only the overworld. Since TerraForged replaces the default overworld generation I think it may not be considered the overworld as far as that code is concerned. I have a different method to use instead in mind for the next update. This will also hopefully be tied in with a config option to disable the whitelisting altogether.

**Comment by Vaelzan** [comment]
Fixed in 14.0.4a and 15.0.3a, just released.
